terms_dict = {
    'open': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'volume': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'sma_30': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH'],
    'rsi': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'macd': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'dia_close': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'dia_volume': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'gld_close': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'gld_volume': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'spy_close': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'spy_volume': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'federal_funds_rate_daily': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'treasury_yield_daily': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'cpi_monthly': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'durables_monthly': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'nonfarm_payroll_monthly': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'real_gdp_per_capita_quarterly': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'real_gdp_quarterly': ['CONSTANT'],
    'retail_sales_monthly': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'unemployment_monthly': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'central_bank_policy_rate_prcnt': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'domestic_credit_gdp': ['CONSTANT'],
    'foreign_direct_investment_value': ['CONSTANT'],
    'gdp_growth_annual_prcnt': ['CONSTANT'],
    'inflation_rate_value': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'individuals_using_the_internet_prcnt_of_population': ['CONSTANT'],
    'mobile_cellular_subscriptions_per_100_people': ['VERY LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'personal_remittances_received_prcnt_of_gdp': ['CONSTANT'],
    'stock_market_index_value': ['CONSTANT'],
    'tariffs_value': ['CONSTANT'],
    'total_public_debt_gdp_value': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH'],
    'trade_balance_value': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'],
    'trade_in_services_value': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH'],
    'unemployment_rate_value': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH'],
    'value': ['CONSTANT'],
    'classification_numerical': ['VERY LOW', 'LOW', 'MEDIUM', 'HIGH'],
}
