terms_dict = {
    "open": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "volume": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "sma_30": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "rsi": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "macd": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "dia_close": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "dia_volume": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "gld_close": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "gld_volume": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "spy_close": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "spy_volume": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "federal_funds_rate_daily": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "treasury_yield_daily": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "cpi_monthly": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "durables_monthly": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "nonfarm_payroll_monthly": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "real_gdp_per_capita_quarterly": ["LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "real_gdp_quarterly": ["CONSTANT"],
    "retail_sales_monthly": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "unemployment_monthly": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "central_bank_policy_rate_prcnt": ["CONSTANT"],
    "domestic_credit_gdp": ["VERY_LOW", "LOW", "MEDIUM", "HIGH"],
    "foreign_direct_investment_value": ["VERY_LOW", "LOW", "MEDIUM", "HIGH"],
    "gdp_growth_annual_prcnt": ["CONSTANT"],
    "inflation_rate_value": ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "individuals_using_the_internet_prcnt_of_population": ["CONSTANT"],
    "mobile_cellular_subscriptions_per_100_people": [
        "VERY_LOW",
        "LOW",
        "MEDIUM",
        "HIGH",
        "VERY_HIGH",
    ],
    "personal_remittances_received_prcnt_of_gdp": ["VERY_LOW", "LOW", "MEDIUM", "HIGH"],
    "stock_market_index_value": ["CONSTANT"],
    "tariffs_value": ["CONSTANT"],
    "total_public_debt_gdp_value": ["VERY_LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
    "trade_balance_value": ["CONSTANT"],
    "trade_in_services_value": ["VERY_LOW", "LOW", "MEDIUM", "HIGH"],
    "unemployment_rate_value": ["CONSTANT"],
    "value": ["CONSTANT"],
    "classification_numerical": ["CONSTANT"],
}
