# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (Cement IS cluster1) AND (BlastFurnaceSlag IS cluster1) AND (FlyAsh IS cluster1) AND (Water IS cluster1) AND (Superplasticizer IS cluster1) AND (CoarseAggregate IS cluster1) AND (FineAggregate IS cluster1) AND (Age IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (Cement IS cluster2) AND (BlastFurnaceSlag IS cluster2) AND (FlyAsh IS cluster2) AND (Water IS cluster2) AND (Superplasticizer IS cluster2) AND (CoarseAggregate IS cluster2) AND (FineAggregate IS cluster2) AND (Age IS cluster2) THEN (OUTPUT IS fun2)"
RULE3 = "IF (Cement IS cluster3) AND (BlastFurnaceSlag IS cluster3) AND (FlyAsh IS cluster3) AND (Water IS cluster3) AND (Superplasticizer IS cluster3) AND (CoarseAggregate IS cluster3) AND (FineAggregate IS cluster3) AND (Age IS cluster3) THEN (OUTPUT IS fun3)"
FS.add_rules([RULE1, RULE2, RULE3])

FS.set_output_function('fun1', '9.429733e-02*Cement+8.117860e-02*BlastFurnaceSlag+6.350147e-02*FlyAsh+-2.608512e-01*Water+1.711752e-01*Superplasticizer+-6.152199e-03*CoarseAggregate+-1.311590e-02*FineAggregate+1.240325e-01*Age+5.696296e+01')
FS.set_output_function('fun2', '1.329767e-01*Cement+1.191859e-01*BlastFurnaceSlag+9.951164e-02*FlyAsh+-1.129952e-01*Water+3.856726e-01*Superplasticizer+3.166177e-02*CoarseAggregate+3.103905e-02*FineAggregate+1.466998e-01*Age+-5.866414e+01')
FS.set_output_function('fun3', '1.087516e-01*Cement+8.807668e-02*BlastFurnaceSlag+6.670191e-02*FlyAsh+-1.548100e-01*Water+5.185396e-01*Superplasticizer+1.031120e-02*CoarseAggregate+1.056331e-02*FineAggregate+1.327843e-01*Age+-4.035711e+00')

FS_1 = FuzzySet(function=Gaussian_MF(403.601021, 134.020348), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(210.632573, 131.658654), term='cluster2')
FS_3 = FuzzySet(function=Gaussian_MF(239.523268, 140.914750), term='cluster3')
MF_Cement = LinguisticVariable([FS_1, FS_2, FS_3], concept='Cement' , universe_of_discourse=(102.0, 540.0))
FS.add_linguistic_variable('Cement', MF_Cement)

FS_4 = FuzzySet(function=Gaussian_MF(-140.733181, 274.264488), term='cluster1')
FS_5 = FuzzySet(function=Gaussian_MF(-88.477381, 215.814048), term='cluster2')
FS_6 = FuzzySet(function=Gaussian_MF(209.200830, 121.470034), term='cluster3')
MF_BlastFurnaceSlag = LinguisticVariable([FS_4, FS_5, FS_6], concept='BlastFurnaceSlag' , universe_of_discourse=(0.0, 359.4))
FS.add_linguistic_variable('BlastFurnaceSlag', MF_BlastFurnaceSlag)

FS_7 = FuzzySet(function=Gaussian_MF(-22.122344, 144.108028), term='cluster1')
FS_8 = FuzzySet(function=Gaussian_MF(119.432548, 97.743967), term='cluster2')
FS_9 = FuzzySet(function=Gaussian_MF(-119.001316, 259.335299), term='cluster3')
MF_FlyAsh = LinguisticVariable([FS_7, FS_8, FS_9], concept='FlyAsh' , universe_of_discourse=(0.0, 200.1))
FS.add_linguistic_variable('FlyAsh', MF_FlyAsh)

FS_10 = FuzzySet(function=Gaussian_MF(187.432134, 45.220545), term='cluster1')
FS_11 = FuzzySet(function=Gaussian_MF(167.714062, 49.879982), term='cluster2')
FS_12 = FuzzySet(function=Gaussian_MF(193.895000, 48.396482), term='cluster3')
MF_Water = LinguisticVariable([FS_10, FS_11, FS_12], concept='Water' , universe_of_discourse=(121.75, 237.0))
FS.add_linguistic_variable('Water', MF_Water)

FS_13 = FuzzySet(function=Gaussian_MF(-16.110731, 44.455843), term='cluster1')
FS_14 = FuzzySet(function=Gaussian_MF(8.475327, 11.774242), term='cluster2')
FS_15 = FuzzySet(function=Gaussian_MF(-2.797941, 20.568248), term='cluster3')
MF_Superplasticizer = LinguisticVariable([FS_13, FS_14, FS_15], concept='Superplasticizer' , universe_of_discourse=(0.0, 32.2))
FS.add_linguistic_variable('Superplasticizer', MF_Superplasticizer)

FS_16 = FuzzySet(function=Gaussian_MF(968.099446, 130.572786), term='cluster1')
FS_17 = FuzzySet(function=Gaussian_MF(999.104941, 131.666180), term='cluster2')
FS_18 = FuzzySet(function=Gaussian_MF(974.014875, 121.812168), term='cluster3')
MF_CoarseAggregate = LinguisticVariable([FS_16, FS_17, FS_18], concept='CoarseAggregate' , universe_of_discourse=(801.0, 1145.0))
FS.add_linguistic_variable('CoarseAggregate', MF_CoarseAggregate)

FS_19 = FuzzySet(function=Gaussian_MF(768.782699, 141.064002), term='cluster1')
FS_20 = FuzzySet(function=Gaussian_MF(798.077570, 128.222938), term='cluster2')
FS_21 = FuzzySet(function=Gaussian_MF(750.013673, 139.866037), term='cluster3')
MF_FineAggregate = LinguisticVariable([FS_19, FS_20, FS_21], concept='FineAggregate' , universe_of_discourse=(594.0, 992.6))
FS.add_linguistic_variable('FineAggregate', MF_FineAggregate)

FS_22 = FuzzySet(function=Gaussian_MF(-167.678919, 382.445126), term='cluster1')
FS_23 = FuzzySet(function=Gaussian_MF(-95.273021, 294.251495), term='cluster2')
FS_24 = FuzzySet(function=Gaussian_MF(-173.236471, 397.550942), term='cluster3')
MF_Age = LinguisticVariable([FS_22, FS_23, FS_24], concept='Age' , universe_of_discourse=(1.0, 365.0))
FS.add_linguistic_variable('Age', MF_Age)


# end of automatically generated code #

def get_cement_fs():
    return FS